### ISSUE TITLE
Cant get base metals mod to regen on existing world

### ISSUE THREAD

**Issue by Luckyday84** [cpw/simpleretrogen#2]
I'm sure I'm missing something simple but do you have any instructions to help me out?

**Comment by The-Fireplace** [comment]
What did you do?

**Comment by Luckyday84** [comment]
I just used the NeoTech mod instead of the Base Metals mod. NeoTech has a has this on the summary to put in the Simple Retrogen config -  com.dyonovan.neotech.world.NeotechWorldGenerator

**Comment by Laikulo** [comment]
I was able to do this with `cyano.basemetals.worldgen.OreSpawner` and It worked just fine.

My full config:

```
# Configuration file

general {
    # Marker to apply to chunks to indicate retrogen occurred
    S:marker=bmRegen

    # Maximum number of retrogens to run in a single tick
    I:maxPerTick=100

    # List of IWorldGenerator instances to fire retrogen for
    S:worldGens <
        cyano.basemetals.worldgen.OreSpawner
     >
```

**Comment by ghost** [comment]
This isn't working for me, too....

**Comment by Laikulo** [comment]
@Dragonfire300 What config are you using? Also, check your startup for messages from SimpleRetroGen, if it does not find a specified class, it'll whine about it.

Also, if you ran the mod with no world-gens specified, you may need to change the marker so chunks will be processed again.

**Comment by ghost** [comment]
I usee the config you posted with several markers and an extra } at the end. I can send you the log later. I used mostly [this](http://minecraft.curseforge.com/projects/enlight/files/2287563) setup. Now im using another mod and everything works fine...

**Comment by ghost** [comment]
sorry, i wasn't able to copy the whole log, but the only times "retrogen" apeared was when forge listed the loaded mods etc....

**Comment by cpw** [comment]
I've reshuffled the config file a bit with 1.9 - other mods will be able to provide direct copy/paste snippets to put into the retrogen config file. You'll just activate them by adding them to a list (and probably, even, a command later).
