### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by SDUBZ** [cpw/simpleretrogen#3]
is it possible to make a listable way of getting all IWorldGenerator in your modlist etc like a command /list IWorldGenerator all or something similar

**Comment by Sailren** [comment]
true, would be interesting to get a command that prints out all worldgenerator stuff so we can feed them to the config

**Comment by Phonavis** [comment]
I agree, it would be pretty useful.
Though i'm still trying to figure out how to get one normally, since Botania doesn't have anything in its configs to retrogen the flowers...

**Comment by Laikulo** [comment]
If you put a bogus class in, The mod will fail to find the bogus classe, and then it will print the classnames and hashcodes of all instances of classes that implement IWorldGenerator.

While not an ideal situation, it works.

**Comment by cpw** [comment]
Added a command in new version "listretrogenclasstargets" which will list all the retrogen classes on the server.

**Comment by Sailren** [comment]
thx bud, best feature ever :D
