### ISSUE TITLE
Does listretrogenclasstargets work in 1.8.9?

### ISSUE THREAD

**Issue by mmalfatti** [cpw/simpleretrogen#5]
Tried it and got "unknown command".

I running on a Mac 10.11.4. minecraft 1.8.9, forge 1855, retrogen 1.8.9-2.2.2+3.

Thank you,
Mike Malfatti

**Comment by cpw** [comment]
No. Sorry, didn't have time to backport it.

**Comment by mmalfatti** [comment]
Thanks for the reply.

If you don’t mind me asking, how would one go about finding the name of worldgen routine of mods?

Thanks again,
Mike.

**Comment by cpw** [comment]
You just have to know the mod, sorry..

**Comment by cpw** [comment]
Not gonna backport to 1.8.9, sorry.
