### ISSUE TITLE
Config file help - Adding more than 1 Generator class

### ISSUE THREAD

**Issue by acokeaday** [cpw/simpleretrogen#6]
Hi,

First of all, Thank you for the mod, it allows us to add mods and yet not worry about travelling further out to get the new ores.

I would like to confirm the syntax on adding more than 1 IWorldGenerator class, is this right?

CPWRGMARK {
    # World Generator classes for marker
    S:worldGens <
slimeknights.tconstruct.shared.worldgen.NetherOreGenerator
com.dyonovan.neotech.world.NeotechWorldGenerator
vazkii.quark.world.world.ClayGenerator
vazkii.quark.world.world.BiotiteGenerator
vazkii.quark.world.world.BasaltGenerator
     >
}

general {
    # Active markers
    S:markerList <
        CPWRGMARK
     >

```
# Maximum number of retrogens to run in a single tick
I:maxPerTick=100
```

}

**Comment by cpw** [comment]
Yup, that's one way. You can have more than one mark as well, and each can have it's own set of gens. That way, if you add more later, you can just add new marks for the new stuff each time and not worry about regenerating older "retrogen".
