### ISSUE TITLE
Crash soon after entering world. MC 1.9

### ISSUE THREAD

**Issue by xhaavardx** [cpw/simpleretrogen#7]
Soon after entering a world, like 1 min, when I start moving around suddenly the game crashes. Here are the most relevant details of my setup:
- Minecraft 1.9
- Simple Retrogen 2.2.3+4
- Forge 12.16.1.1938
- A config file full of worldgen classes (all retrieved by the /listretrogenclasstargets command)

[Crash Log](http://paste.ee/p/JkUfb)
[Full log - start to finish](https://paste.ee/p/A6F8q)

Excerpt from crash log:

> java.lang.NullPointerException: Exception in server tick loop
>     at cpw.mods.retro.WorldRetrogen$TargetWorldWrapper.access$400(WorldRetrogen.java:309)
>     at cpw.mods.retro.WorldRetrogen.runRetrogen(WorldRetrogen.java:449)
>     at cpw.mods.retro.WorldRetrogen.access$900(WorldRetrogen.java:78)
>     at cpw.mods.retro.WorldRetrogen$LastTick.tickStart(WorldRetrogen.java:303)
>     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_443_LastTick_tickStart_WorldTickEvent.invoke(.dynamic)
>     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
>     at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
>     at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:261)
>     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:714)
>     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609)
>     at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
>     at java.lang.Thread.run(Thread.java:745)

What is causing this?
Is it because of possible defunct worldgen classes in the config?

**Comment by Nincodedo** [comment]
Could you include your config file as well?

**Comment by xhaavardx** [comment]
Here you go @Nincodedo  :)

CPWRGMARK {
    # World Generator classes for marker
    S:worldGens <
        com.dyonovan.neotech.world.NeotechWorldGenerator
        de.ellpeck.actuallyadditions.mod.gen.OreGen
        com.kashdeya.simpleupgrades.world.SimpleUpgradesWorldgen
        mcjty.rftools.world.RFToolsWorldGenerator
        mcjty.deepresonance.worldgen.DeepWorldGenerator
        mcjty.rftoolsdim.dimensions.world.GenericWorldGenerator
        mod.lucky.world.LuckyGenerator
        slimeknights.tconstruct.shared.worldgen.NetherOreGenerator
        slimeknights.tconstruct.world.worldgen.SlimeIslandGenerator
        slimeknights.tconstruct.world.worldgen.MagmaSlimeIslandGenerator
        lumien.randomthings.worldgen.WorldGenPlants
        lumien.randomthings.worldgen.WorldGenCores
        net.kaneka.planttech.schematicwork.SchematicGeneratorLFI
        com.kashdeya.simpleupgrades.handlers.BedrockHandler
        vazkii.quark.world.world.BiotiteGenerator
        vazkii.quark.world.world.ClayGenerator
        vazkii.quark.world.world.BasaltGenerator
        com.pam.harvestcraft.worldgen.FruitTreeWorldGen
        com.pam.harvestcraft.worldgen.BushWorldWorldGen
        com.pam.harvestcraft.worldgen.LogFruitTreeWorldGen
        net.silentchaos512.funores.world.FunOresGenerator
        plantmegapack.worldgen.PMPWorldGenerator
        cyano.basemetals.worldgen.OreSpawner
        com.tomevoll.routerreborn.Blocks.ore.OreGenerator
        com.knoxhack.nethermetals.world.WorldGen
        techreborn.world.TechRebornWorldGen
        net.silentchaos512.gems.world.GemsWorldGenerator
        com.rbs.slurpiesdongles.world.SlurpiesDonglesWorldGenerator
        net.armedmob.mcclassified.worldgen.MCCWorldGen
        dmf444.ExtraFood.Common.WorldGen.PeanutWorldGen
        mod.mcreator.PackedOres
        sugiforest.handler.SugiWorldGenerator
        atomicstryker.ruins.common.RuinsMod$RuinsWorldGenerator
        com.shinoow.abyssalcraft.common.world.AbyssalCraftWorldGenerator
        cd4017be.automation.Automation
        greymerk.roguelike.DungeonGenerator
     >

general {
    # Active markers
    S:markerList <
      CPWRGMARK
     >

```
# Maximum number of retrogens to run in a single tick
I:maxPerTick=100
```

}

**Comment by The-Fireplace** [comment]
Same crash here on 1.9.4, except it happens when I try to load a world, not after the world is loaded. Here is my config:

# Configuration file

##########################################################################################################

# CPWRGMARK

#--------------------------------------------------------------------------------------------------------#

# Marker definition

# You can create as many of these as you wish

# Activate by adding to active list

##########################################################################################################

CPWRGMARK {
    # World Generator classes for marker
    S:worldGens <
        "com.valkyrieofnight.environmentaltech.world.WorldGen"
     >
}

cpwrgmark {
    S:worldGens <
        "com.valkyrieofnight.environmentaltech.world.WorldGen"
     >
}

general {
    # Active markers
    S:markerList <
        CPWRGMARK
     >

```
# Maximum number of retrogens to run in a single tick
I:maxPerTick=100
```

}
