### ISSUE TITLE
Failed to save chunks

### ISSUE THREAD

**Issue by dannydjdk** [cpw/simpleretrogen#8]
I had an issue in my world where Minecraft was unable to save chunks. When attempting to save, the following message was spammed in the game log:

```
[File IO Thread/ERROR]: Failed to save chunk
java.lang.NullPointerException
```

Disabling Simple Retrogen eliminates the problem (though it sadly did not bring back my hours of building and landscaping). Re-enabling it re-introduces the problem.

My config file is as follows:

```
# Configuration file

##########################################################################################################
# CPWRGMARK
#--------------------------------------------------------------------------------------------------------#
# Marker definition
# You can create as many of these as you wish
# Activate by adding to active list
##########################################################################################################

CPWRGMARK {
    # World Generator classes for marker
    S:worldGens <
        forestry.core.worldgen.WorldGenerator
     >
}


cpwrgmark {
    S:worldGens <
        forestry.core.worldgen.WorldGenerator
     >
}


general {
    # Active markers
    S:markerList <
        CPWRGMARK
     >

    # Maximum number of retrogens to run in a single tick
    I:maxPerTick=100
}
```

I had previously configured it to retro gen Deep Resonance world gen, and it worked fine. After changing the config to the above for Forestry, the above problem occurred resulting in loss of all changes in world, though player data did save.

**Comment by FiveEYZ** [comment]
@cpw sorry to bother you but I saw `[File IO Thread/ERROR]: Failed to save chunk` in this issue, it makes me wonder if my error is related to this? 
https://gist.github.com/FiveEYZ/287342a1385a49156c5a4e0719c16f7e
(I see this error every now and then in console.)

If no, do you possible know where i could turn or is my world lost beyond saving?
