### ISSUE TITLE
found line duplication is there a way to fix? eg:config option

### ISSUE THREAD

**Issue by SDUBZ** [cpw/simpleretrogen#9]
when using orespawn mod i got 70 duplications of the same line example rcyano.orespawn.worldgen.OreSpawner x70 of same line of worldgen
[list of simpleretorgen.txt](https://github.com/cpw/simpleretrogen/files/314436/list.of.simpleretorgen.txt)
 would be nice to remove dupes from listings if possible

**Comment by cpw** [comment]
No. In fact, that list is completely unusable to simpleretrogen, because it's dozens of instances of the same class registered to the world generators. I can't distinguish between any of them, and neither can you.
